### ISSUE TITLE
ClickHouse 23.10 support

### ISSUE THREAD

**Issue by Alex-Burmak** [yandex/ch-backup#84]
The following test scenario fails for ClickHouse 23.10: 

```
  Scenario: Backup table with S3 storage policy                   # tests/integration/features/backup_multiple_disks.feature:39
    Given default configuration                                   # tests/integration/steps/common.py:12
    And a working s3                                              # tests/integration/steps/s3.py:12
    And a working clickhouse on clickhouse01                      # tests/integration/steps/clickhouse.py:15
    And a working clickhouse on clickhouse02                      # tests/integration/steps/clickhouse.py:15
    Given we have executed queries on clickhouse01                # tests/integration/steps/clickhouse.py:55
      """
      CREATE DATABASE IF NOT EXISTS test_db;
      CREATE TABLE test_db.table_01 (
          CounterID UInt32,
          UserID UInt32
      )
      ENGINE = MergeTree()
      PARTITION BY CounterID % 3
      ORDER BY UserID
      SETTINGS storage_policy = 's3';
      
      INSERT INTO test_db.table_01 SELECT 0, number FROM system.numbers LIMIT 10;
      INSERT INTO test_db.table_01 SELECT 1, number FROM system.numbers LIMIT 10;
      """
    When we create clickhouse01 clickhouse backup                 # tests/integration/steps/ch_backup.py:26
    Then we got the following backups on clickhouse01             # tests/integration/steps/ch_backup.py:146
      | num | state   | data_count | link_count |
      | 0   | created | 2          | 0          |
    When we restore clickhouse backup #0 to clickhouse02          # tests/integration/steps/ch_backup.py:86
      """
      cloud_storage_source_bucket: 'cloud-storage-01'
      cloud_storage_source_path: 'data'
      """
      Assertion Failed: execution failed with code 1, out: "Traceback (most recent call last):
        File "/usr/local/bin/ch-backup", line 33, in <module>
          sys.exit(load_entry_point('ch-backup', 'console_scripts', 'ch-backup')())
        File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
          return self.main(*args, **kwargs)
        File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
          rv = self.invoke(ctx)
        File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
          return _process_result(sub_ctx.command.invoke(sub_ctx))
        File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
          return ctx.invoke(self.callback, **ctx.params)
        File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
          return __callback(*args, **kwargs)
        File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
          return f(get_current_context(), *args, **kwargs)
        File "/var/tmp/ch-backup/ch_backup/cli.py", line 161, in wrapper
          result = ctx.invoke(f, ctx, ctx.obj["backup"], *args, **kwargs)
        File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
          return __callback(*args, **kwargs)
        File "/var/tmp/ch-backup/ch_backup/cli.py", line 693, in restore_command
          ch_backup.restore(
        File "/var/tmp/ch-backup/ch_backup/ch_backup.py", line 291, in restore
          self._restore(
        File "/var/tmp/ch-backup/ch_backup/ch_backup.py", line 521, in _restore
          self._table_backup_manager.restore(
        File "/var/tmp/ch-backup/ch_backup/logic/table.py", line 267, in restore
          self._restore_data(
        File "/var/tmp/ch-backup/ch_backup/logic/table.py", line 607, in _restore_data
          disks.copy_part(context.backup_meta, table, part)
        File "/var/tmp/ch-backup/ch_backup/clickhouse/disks.py", line 160, in copy_part
          self._copy_dir(
        File "/var/tmp/ch-backup/ch_backup/clickhouse/disks.py", line 190, in _copy_dir
          result = _exec(
        File "/var/tmp/ch-backup/ch_backup/clickhouse/disks.py", line 222, in _exec
          raise ClickHouseDisksException(
      ch_backup.clickhouse.disks.ClickHouseDisksException: clickhouse-disks call failed with exitcode: 70
```

https://github.com/yandex/ch-backup/actions/runs/6737760412/job/18315952124#logs

**Comment by MikhailBurdukov** [comment]
More details:
clickhouse-disks logs:
```
root@clickhouse02:/# /usr/bin/clickhouse-disks --log-level TRACE copy --disk-from s3_source --disk-to s3 shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/ store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/
Provider type: Unknown
API mode of the S3 client: AWS
Starting up disk s3_source
Disk s3_source started up
Provider type: Unknown
API mode of the S3 client: AWS
Starting up disk s3
Disk s3 started up
Loading filesystem cache with 1 threads
Status file /var/lib/clickhouse/disks/s3_cache/status already exists - unclean restart. Contents:
PID: 13
Started at: 2023-11-07 10:59:34
Revision: 54479

Code: 76. DB::Exception: Cannot lock file /var/lib/clickhouse/disks/s3_cache/status. Another server instance in same directory is already running. (CANNOT_OPEN_FILE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cdd11b7 in /usr/bin/clickhouse
1. DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x00000000079a084d in /usr/bin/clickhouse
2. DB::StatusFile::StatusFile(String, std::function<void (DB::WriteBuffer&)>) @ 0x000000000cf0bdff in /usr/bin/clickhouse
3. DB::FileCache::initialize() @ 0x0000000012c14c05 in /usr/bin/clickhouse
4. DB::CachedObjectStorage::CachedObjectStorage(std::shared_ptr<DB::IObjectStorage>, std::shared_ptr<DB::FileCache>, DB::FileCacheSettings const&, String const&) @ 0x0000000011dac72e in /usr/bin/clickhouse
5. DB::DiskObjectStorage::wrapWithCache(std::shared_ptr<DB::FileCache>, DB::FileCacheSettings const&, String const&) @ 0x0000000011dac04a in /usr/bin/clickhouse
6. std::shared_ptr<DB::IDisk> std::__function::__policy_invoker<std::shared_ptr<DB::IDisk> (String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&)>::__call_impl<std::__function::__default_alloc_func<DB::registerDiskCache(DB::DiskFactory&, bool)::$_0, std::shared_ptr<DB::IDisk> (String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&)>>(std::__function::__policy_storage const*, String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>&&, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&) (.llvm.8578554134549538779) @ 0x0000000011de4748 in /usr/bin/clickhouse
7. DB::DiskFactory::create(String const&, Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::map<String, std::shared_ptr<DB::IDisk>, std::less<String>, std::allocator<std::pair<String const, std::shared_ptr<DB::IDisk>>>> const&) const @ 0x0000000011d62c60 in /usr/bin/clickhouse
8. DB::DiskSelector::initialize(Poco::Util::AbstractConfiguration const&, String const&, std::shared_ptr<DB::Context const>, std::function<bool (Poco::Util::AbstractConfiguration const&, String const&)>) @ 0x0000000011f22080 in /usr/bin/clickhouse
9. DB::Context::getDiskSelector(std::lock_guard<std::mutex>&) const @ 0x0000000011ee96fd in /usr/bin/clickhouse
10. DB::Context::getDisk(String const&) const @ 0x0000000011ecbda0 in /usr/bin/clickhouse
11. DB::CommandCopy::execute(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::Context>&, Poco::Util::LayeredConfiguration&) @ 0x000000000d0937b2 in /usr/bin/clickhouse
12. DB::DisksApp::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000d08d88e in /usr/bin/clickhouse
13. Poco::Util::Application::run() @ 0x000000001659e0e6 in /usr/bin/clickhouse
14. mainEntryClickHouseDisks(int, char**) @ 0x000000000d08fff8 in /usr/bin/clickhouse
15. main @ 0x00000000073badfa in /usr/bin/clickhouse
16. ? @ 0x0000000000023d0a in /lib/x86_64-linux-gnu/libc-2.31.so
17. _start @ 0x00000000065903ae in /usr/bin/clickhouse
 (version 23.10.1.1976 (official build))
DB::Exception: Cannot lock file /var/lib/clickhouse/disks/s3_cache/status. Another server instance in same directory is already running.
Shutting down named sessions
Shutting down database catalog
Shutting down system databases
Shutting down DDLWorker
Shutting down caches
```

**Comment by MikhailBurdukov** [comment]
After stopping clickhouse-server on the same node, `copy` cmd works normally:
```
root@clickhouse02:/# supervisorctl stop clickhouse 
clickhouse: stopped
root@clickhouse02:/# /usr/bin/clickhouse-disks --log-level TRACE copy --disk-from s3_source --disk-to s3 shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/ store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/
Provider type: Unknown
API mode of the S3 client: AWS
Starting up disk s3_source
Disk s3_source started up
Provider type: Unknown
API mode of the S3 client: AWS
Starting up disk s3
Disk s3 started up
Loading filesystem cache with 1 threads
Registered cached disk (`s3_cache`) with structure: DiskObjectStorage-s3(CachedObjectStorage-s3_cache(S3ObjectStorage))
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/default_compression_codec.txt to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/default_compression_codec.txt.
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/partition.dat to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/partition.dat.
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/count.txt to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/count.txt.
Create WriteBufferFromS3, Details: bucket cloud-storage-02, key data/oic/fiudvqoqntynsqxavaeltyemdbhoa
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/data.bin to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/data.bin.
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/columns.txt to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/columns.txt.
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/serialization.json to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/serialization.json.
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/checksums.txt to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/checksums.txt.
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/primary.cidx to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/primary.cidx.
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/minmax_CounterID.idx to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/minmax_CounterID.idx.
Copying from s3_source (path: /var/lib/clickhouse/disks/s3_source/) shadow/77970e61_7626_4fd1_8925_dec40fad4677/store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/1_2_2_0/data.cmrk3 to s3 (path: /var/lib/clickhouse/disks/s3/) store/72f/72f5d0a7-61e7-45a7-9183-62e9366a1373/detached/1_2_2_0/data.cmrk3.
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Created HTTP(S) session with minio01:9000 (10.199.166.5:9000)
Single part upload has completed. Details: bucket cloud-storage-02, key data/oic/fiudvqoqntynsqxavaeltyemdbhoa, size 10
finalizeImpl WriteBufferFromS3. Details: bucket cloud-storage-02, key data/oic/fiudvqoqntynsqxavaeltyemdbhoa.
Close WriteBufferFromS3. Details: bucket cloud-storage-02, key data/oic/fiudvqoqntynsqxavaeltyemdbhoa.
Destructing remote fs threadpool reader
Destructing local fs threadpool reader
Destructing local fs threadpool reader
Shutting down named sessions
Shutting down database catalog
Shutting down system databases
Shutting down DDLWorker
Shutting down caches
```

**Comment by MikhailBurdukov** [comment]
Assume that starting breaks from this pr : https://github.com/ClickHouse/ClickHouse/pull/55002
